### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/bridge-nodejs#4]
Think about how we can increase performance

1. 
since there are 3 modules: one way would be run 3 separate processes: deposits, withdrawals, collectedSignatures
the only problem is shared nonce between process deposits and withdrawals

2. Think about what we can utilize for multicore workers
https://nodejs.org/api/cluster.html

**Comment by rstormsf** [comment]
there is ZeroMQ and RabbitMQ
https://stackoverflow.com/questions/731233/activemq-or-rabbitmq-or-zeromq-or

**Comment by fvictorio** [comment]
This is our understanding of how this would work. Please let us know if we are missing or misunderstanding something.

There are events emitted both in the home and foreign chains. *All* bridges instances (each one with a different private key) need to listen to all these events. This listening could be divided in different processes, one per event, but there will be N "copies" of each process, one per PK.

This layer of watchers will create jobs in the queue. I guess these jobs will have the transactions already signed and with the proper nonce, but I may be missing something here.

Finally, we have two consumers: one for the home chain and the other for the foreign chain. These consumers don't need the private keys, and there's no need to have N of each one. They just fetch a job, propagate that signed transaction in the proper chain, handle possible errors, etc.

Theoretically, these consumers could be horizontally scaled (not so the bridges, since duplicating them would allow a single event to be processed twice by the same validator). It seems to me that this scaling wouldn't be of great benefit, since the processing of those jobs is I/O bound, and node excels on that, but it could be done if necessary.

Is this correct?

**Comment by fvictorio** [comment]
Regarding the queue service, I thinks ZeroMQ is too low level for this application. Even RabbitMQ seems a little overkill, but I don't know of a better alternative (we've used [Kue](https://github.com/Automattic/kue), which creates job queues using redis, but I didn't like it).

**Comment by akolotov** [comment]
Thanks @fvictorio for summary.
1. I would not consider consumers which will handle 3*N jobs. Because:
  * this architecture requires to have one (or maybe two) queue service for all bridge instances. At the same time it means that queue service will require listen on a public interface and this is definitely decrease security.
  * bridges still need to track their own nonce in two tasks for sending `withdraw()` and `submitSignatures()`. We would like to avoid this by introducing consumers for sending transactions and tracking the nonce.

2. I would say that every bridge instance will have their own set of: processes listening events, queue service and two consumers sending transactions.
  * every consumer will know PK for this particular bridge instance
  * one consumer signs transactions for Home, another consumer signs transactions for Foreign 
  * processes will send jobs to consumers through message queue. Every job will have ABI-encoded `data` field which depends on the method and parameters need to be sent to the contract
  * consumer composes a transaction by using `chain ID`, `nonce`, `data`, `gas price` and `contract address`, signs this transaction by PK and send it 
  * queue service could be deployed in isolated network as so only particular bridge processes could connect to the service
Most probably, this architecture should extended due to requirements from other issues. For example, which part will consider that a transaction was confirmed by enough number of blocks? Or should additional processes be introduced to cover logging requirements?

3. From my perspective since we don't know performance boundaries of nodejs based bridge yet, the main benefits of such architecture are follwoing:
  * since only one consumer is responsible for composing and sending transactions we get rid of issues with nonce;
  * one consumer could stop operating due to insufficient funds whereas another consumer will continue relaying transactions.

**Comment by fvictorio** [comment]
Another option for the queue service is [bull](https://github.com/OptimalBits/bull), that is written for node and uses Redis.

**Comment by fvictorio** [comment]
We've been discussing how to design this and this is a first approach that we think could work.

The general picture is this:

![image](https://user-images.githubusercontent.com/417134/40630604-4a41c986-62aa-11e8-999e-08dca615532d.png)

For each bridge instance (each one with its own private key), we have three "Watchers" and two "Senders". The watchers are independent processes that listen for certain events and create the proper jobs in the queue. These jobs will have, at least, the transaction data (without the nonce). Besides that, the watchers need to keep track of the last block they processed.

Then we have two sender processes: one for sending transactions in the home chain and another for the foreign chain. These senders take jobs from the queue, extract the transaction data, add the proper nonce and send it. They also need to keep track of their nonce.

---

Our idea is to have a npm script for the watchers and another for the senders. We would run the watcher script three times, each one with a different configuration. So the base code would be the same, but they would differ in which event they listen to, in which contract, how they create the transaction data using that event, etc. The pseudo-code would be:

```
Initialize process
Every N seconds:
    Listen to the events since the last block number
    Process these events (The function to use will depend on the event type id)
    Create a job for each event and push them to the queue
    Update last block number used
```

Similarly, each sender will be started with the same npm script, but with different configuration. The pseudo-code for the senders is:

```
For each job fetched from the queue:
    Lock nonce key and get nonce from redis
    Create and sign Tx
    If Tx can be Propagated (just sent, not mined):
        Increment nonce on redis and unlock nonce Key
        Mark job as complete
    Else If propagation fails because the nonce is incorrect:
        Get the correct nonce from the blockchain
        Update it in redis and unlock the key
        Try to process it again or cancel it (job goes back to the queue)
    Else If propagation fails for another reason:
        Unlock the key in redis
        Cancel job (job goes back to the queue)
```

Note that this means that only one job is processed at the same time (since the nonce is locked). The performance of this approach may not be good enough, but it's easy to improve. For example, we could fetch several jobs from the queue, and process them at the same time (the fetch and lock from redis and subsequent increase and unlock would be similar).

In the server, all this processes can be initialized, monitored and kept alive with pm2.

For the queue, RabbitMQ seems like the best option: it's a mature project and has all the features that we need.

**Comment by akolotov** [comment]
Thank @fvictorio for good explanation!
I have few questions:
1. Did you choose redis for storing block numbers? Currently plain-text json allows to modify DB to roll back block number and force the bridge instance to 're-look' for events. It is needed sometimes to trigger events which was skipped by some reason.
2. Could you provide in the description more details how exactly one "watcher script" will be managed to run different watchers? Similar is to run senders.

**Comment by fvictorio** [comment]
1. The reason for using redis is to have locking capabilities, that we don't have when using JSON files. Regarding the rollback: you can connect to it using `redis-cli` and just update the value of the block number.
2. We didn't define that in depth, but I guess something like `npm run watcher -- deposit-watcher-config.json` would be enough. (The `--` is necessary so that npm sends the argument to the script). And similarly for the senders.

**Comment by akolotov** [comment]
@fvictorio did you think about the way to deploy and run radis and rabbitMQ as part of the bridge instance startup sequence as so at least rabbitMQ was accessible through network? Will it be a docker container or what?

**Comment by fvictorio** [comment]
No, I haven't thought about that, but we can try to make a docker container when we have a minimum working example.

**Comment by akolotov** [comment]
Thanks! Please take this need into account when will write a startup code for the solution,
