### ISSUE TITLE
Processing fails when a block has hundreds of transactions

### ISSUE THREAD

**Issue by fvictorio** [poanetwork/bridge-nodejs#64]
See discussion in https://github.com/poanetwork/bridge-nodejs/pull/60.

Create a block with 300 transactions. After processing some of them, the RPC responds with an error. This causes all transactions to be retried later, and fail again.

Possible solutions:

- Retry when a request fails (related to https://github.com/poanetwork/bridge-nodejs/issues/63).
- Set a max size to the number of events that are processed at the same time (this may need some architectural changes).

**Comment by rstormsf** [comment]
Here is what I think is happening:
1. Worker has a loop to ask every X seconds( 5 seconds) to query for new blocks
2. Since our  previous block wasn't fully processed, we still have local db pointed to old block
3. The new RPC request(timeout) should be less than next run to query for new blocks.
So if there are failed RPC requests, all workers should not probably try to fetch information about new transactions.

**Comment by akolotov** [comment]
Addressed in #72.
