### ISSUE TITLE
Extend bridge logging functionality

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-nodejs#8]
It is necessary to extend the logging functionality in order to have information handled and generated by the bridge instance more transparent.
Below is the list of information needed for every type of operation:

1. `processDeposits`
   * tx hash of the transaction (which emitted `Deposit()` event on  _HomeBridge_ contract) including the transaction sender and value;
   * tx hash of the transaction sent by the bridge instance to  _HomeBridge_ contract to approve the deposit including a reference tx hash originated the deposit (it allows to link this transaction to transaction from previous item);
   * information whether `SignedForDeposit()` emitted by transaction from the previous item including the reference tx hash originated the deposit; 
   * tx hashes for transactions which demonstrate that the deposit was handled by other instances (other `SignedForDeposit()` events) with the reference tx hash originated the deposit.

2. `processCollectedSignatures`
   * tx hash of the transaction (which emitted `CollectedSignatures()` event) including information if this bridge instance is responsible for relaying the deposit message;
   * tx hash of the transaction sent by the bridge instance to the _ForeignBridge_ contract including a reference tx hash originated the deposit (it allows to link this transaction to transaction from previous item);
   * information whether respond from _ForeignBridge_ contract (`Deposit()` event) received including the reference tx hash originated the deposit;
   * tx hashes for transaction which demonstrate that the deposit was relayed by other instances (other `Deposit()` events) with the reference tx hash originated the deposit.

3. `processWithdraw`
   * tx hash of the transaction (which emitted `Withdraw()` event on _ForeignBridge_ contract) including the transaction sender and value;
   * tx hash of the transaction sent by the bridge instance to _HomeBridge_ contract to approve withdrawal including a reference tx hash originated the withdrawal (it allows to link this transaction to transaction from previous item);
   * information whether `Withdraw()` emitted by transaction from the previous item including the reference tx hash originated the withdrawal; 
   * tx hashes for transactions which demonstrate that the withdrawal was handled by other instances (other `Withdraw()` events) with the reference tx hash originated the withdrawal.

**Comment by rstormsf** [comment]
I'm not an expert on logging backend in node.js but here is what I suggest:
- use different colors for events in logs. Lets make it look nice! maybe something  like
https://github.com/winstonjs/winston could be helpful
- use different levels of logging

**Comment by akolotov** [comment]
Thanks @rstormsf. But may it be that different colors is "nice to have" since the logs will be re-directed to remote syslog server anyway where terminal escaping sequence to colorize logs could introduce issues with logs parsing. It needs to be tested first.

**Comment by fvictorio** [comment]
I highly recommend [pino](https://github.com/pinojs/pino/). We gave it a try in PoBA and I liked it a lot.

The idea is to have more structured logs (every log is a JSON line), so that they are easier to parse and analyze. And you can use other tools above it for making them easier to understand for humans (for example, when logging to stdout/stderr).

It also has support for child loggers, so for example all logs from different subprocesses have an identifier metadata (some property in the JSON). This fits nicely with the new architecture of sub-processes.

**Comment by patitonar** [comment]
Here is a proposal for the logs:

- Use Pino https://github.com/pinojs/pino/
- Use different levels of logs (error, warn, info, ...)
- Each log will be a JSON line containing the message, timestamp, the validator address and id of process (watcher/sender + event)
- Log Information related to rabbitmq and redis connection status (connected or disconnected)

- Watcher
    - Number of events found.
    - Log if event was already processed.
    - Number of Tx data to Send on a Job.
    - Deposit
        - TxHash, sender and value of the transaction which emitted Deposit event.
    - Collected Signatures
        - TxHash of the transaction which emitted CollectedSignatures event 
        - If bridge instance is responsible for relaying the message.
    - Withdraw
        - TxHash, sender and value of the transaction which emitted Withdraw event.

- Sender (Use job consumerTag and deliveryTag as identifier)
    - Notify that a job was received with the amount of Tx to send.
    - Tx hash generated and Tx hash of reference (to link transactions).
    - If Tx failed: reason of fail and Tx hash of reference.
    - Number of failed Tx to send back to the queue.
    - Finished processing job.

Regarding the logs about the results of the transactions mentioned on the first comment:
- `processDeposits`: information whether SignedForDeposit() emitted by transaction and by other bridge instances.
- `processCollectedSignatures`: information whether respond from ForeignBridge contract (Deposit() event) received and that the deposit was relayed by other instances (other Deposit() events)
- `processWithdraw`: information whether Withdraw() emitted by transaction and that the withdrawal was handled by other instances (other Withdraw() events)

I think that information can be handled as part of a separate Monitoring Tool since the bridge is not listening to those kind of events.

**Comment by fvictorio** [comment]
Besides a logging library, we should have some sort of log management (to aggregate and persist the logs, be able to query and filter them, set up alerts, etc). We have two options here:

We could use a SaaS that handle this for us. I think [Papertrail](https://papertrailapp.com/) is the obvious choice here.

The other option is to use a log management service that can be installed on premises. The advantages of this is not depending on a third party service and having much more flexibility, but of course it would mean investing much more effort and time. If we choose this, the most used options seem to be [Graylog](https://www.graylog.org/) and [ELK](https://www.elastic.co/elk-stack).

**Comment by akolotov** [comment]
@phahulin could you look at the last comment from Franco?

**Comment by phahulin** [comment]
Hey @fvictorio 
we already use papertrail for aggregating logs of the rust version of the bridge. Namely, we forward syslog to the papertrail. So I think it's ok to stick with this service.

**Comment by akolotov** [comment]
@patitonar thanks for detailed description!
Currently I see only one comment from my side. You mentioned `Tx hash generated and Tx hash of reference (to link transactions).` for senders. Does it mean that Tx hash for reference is passed as part of job description through RabbitMQ?

**Comment by patitonar** [comment]
Yes @akolotov right now there are 3 attributes that are passed as part of the job for each event. `Tx data`, `gas estimate` and `Tx hash reference`.

https://github.com/poanetwork/bridge-nodejs/blob/819aa90993237e4c8a19ab5dfb6a406a492322ae/src/events/processDeposits.js#L46-L50

**Comment by akolotov** [comment]
@patitonar  That's great! let's implement logging subsystem as you stated above.
